name: NuGet Package Restore

on:
  push:
    branches:
      - master  # Adjust this to match the branch you want to trigger the workflow on

jobs:
  restore:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'  # Specify the version of .NET to use

      - name: Restore NuGet packages
        run: nuget restore
